x=msgBox("this is a virus",1+48,"virus")


x=msgbox("injecting files",1+48,"virus")

x=msgbox("virus alert | a virus has hacked you",1+48,"virus")

x=msgBox("this is a virus",1+48,"virus")
createObject("sapi.spVoice").speak "computer corrupt"

x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
createObject("sapi.spVoice").speak "don't worry, remember. this is only a fake malware i put together"
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
createObject("sapi.spVoice").speak "you were hacked"


createObject("sapi.spVoice").speak "i have hacked your computer. and you can't stop me"
createObject("sapi.spVoice").speak "uwu"

x=msgBox("error",1+48,"virus")
x=msgbox("thanks for trying this fake malware",1+48,"creator")
x=msgbox("https://www.youtube.com/watch?v=9J62hGda9BQ&t=61s",1+48,"creator")
createObject("sapi.spVoice").speak "you really thought, this was over? your device password is hash hash hash hash"
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
x=msgBox("this is a virus",1+48,"virus")
createObject("sapi.spVoice").speak "good job! but it still ain't. over"